#!/bin/bash

base_path=/tmp

cd "$base_path"

tobucketfile="$(mktemp -u XXXXXXXXXXXX)_$(uname -n)_$(date +%FT%T%z)"
s3endpoint="{{ s3_endpoint }}"


awk '
function json_keyval_obj(field, memval) {
    return sprintf("{\"%s\":\"%d\"}", field, memval)
}

/Mem|Cache|Swap/ {
    i++
    fields[i]    = substr($1, 1, length($1)-1) # Drop the : char at the end
    memvalues[i] = sprintf("%d", $2)           # Output values in default KB
}

END {
    # This is used to leave out
    # the comma after the last element.
    last = i

    # Constructing the output JSON.
    out="{\"MemoryValues\":["
    for(j=1;j<=i;j++) {
        out = out json_keyval_obj(fields[j], memvalues[j])
        if (j<last) out = out ","
    }
    out = out "]}"

    print(out)

}' /proc/meminfo > "$tobucketfile"


AWS_ACCESS_KEY_ID='{{ aws_access_key_id }}' \
    AWS_SECRET_ACCESS_KEY='{{ aws_secret_access_key }}' \
        aws s3 cp --quiet "$tobucketfile" s3://"$s3endpoint/$tobucketfile"

