#!/bin/bash

base_path=/tmp

cd "$base_path"

# AWS magick IP whence you can query metadata about your EC2 instances!
aws_instance="$(curl -s --connect-timeout 1 http://169.254.169.254/latest/meta-data/instance-id)"

metrics_json="$(mktemp -u XXXXXXXXXXXX)_$(uname -n)_${aws_instance}_$(date +%FT%T%z)"


awk '

/Mem|Cache|Swap/ {
    i++
    fields[i]  = substr($1, 1, length($1)-1) # Drop the : char at the end
    memvalues[i] = sprintf("%d", $2)           # Output values in default KB
}

END {
    # This is used to leave out
    # the comma after the last element.
    last = i

    q = "\""

    # Constructing the output JSON.
    out="["
    for(j=1;j<=i;j++) {
        out = out "{" q "MetricName" q ":" q fields[j] q ","
        out = out q "Timestamp" q ":" q strftime("%FT%T%z") q ","
        out = out q "Value" q ":" sprintf("%d", memvalues[j]) ","
        out = out q "Unit" q ":" q "Kilobytes" q
        out = out "}"
        if (j<last) out = out ","
    }
    out = out "]"

    print(out)

}' /proc/meminfo > "$metrics_json"

AWS_ACCESS_KEY_ID='{{ aws_access_key_id }}' \
    AWS_SECRET_ACCESS_KEY='{{ aws_secret_access_key }}' \
        aws cloudwatch put-metric-data \
            --region "{{ cloudwatch_region }}" \
            --namespace "{{ cloudwatch_namespace }}" \
            --metric-data file://"$metrics_json"

